/**
 * Central site configuration — single source of truth for company/legal
 * identity, the conversion CTAs (book-a-call, pilot), and the generated
 * catalog-PDF download URLs.
 *
 * Imported by the footer, legal pages, the book-a-call modal, the pilot
 * form, and the catalog-PDF script. Keep values here, not inline.
 */

// ---- Company / legal identity -------------------------------------------
export const COMPANY = {
  legalName: "Echelix, LLC",
  shortName: "Echelix",
  domain: "echelix.app",
  siteUrl: "https://echelix.app",
  // Echelix is organized as a Delaware limited liability company.
  jurisdiction: "State of Delaware, United States",
  governingLaw: "State of Delaware, United States",
  location: "Wilmington, Delaware, United States",
  tagline: "Modernize. Build Agentic Apps. Deliver Business Value.",
  // Contact addresses (route mailboxes as you like in M365).
  email: {
    general: "hello@echelix.app",
    privacy: "privacy@echelix.app",
    legal: "legal@echelix.app",
    accessibility: "accessibility@echelix.app",
    security: "security@echelix.app",
    sales: process.env.SALES_NOTIFICATION_EMAIL || "sales@echelix.app",
  },
} as const;

// Effective/last-updated date stamped on the legal pages.
// Bump when the policies change.
export const LEGAL_EFFECTIVE_DATE = "June 2, 2026";

// ---- Outlook Bookings (discovery / consultation call) -------------------
// Public Bookings page URL, e.g.
//   https://outlook.office365.com/owa/calendar/<your-booking>/bookings/
// Set NEXT_PUBLIC_BOOKINGS_URL in .env.local + Vercel. When unset, the
// book-a-call modal shows a graceful mailto fallback instead of an iframe.
export const BOOKINGS_URL = process.env.NEXT_PUBLIC_BOOKINGS_URL || "";

// ---- Catalog PDF (sales leave-behind) -----------------------------------
// The catalog PDFs are generated by scripts/gen-catalog-pdf.mjs and uploaded
// to Supabase Storage at deterministic (upserted) paths, so these public
// URLs are stable across regenerations.
function publicAsset(path: string): string {
  const base = (process.env.NEXT_PUBLIC_SUPABASE_URL || "").replace(/\/+$/, "");
  if (!base) return "";
  return `${base}/storage/v1/object/public/demo-assets/${path}`;
}

export const CATALOG_PDF = {
  customer: publicAsset("catalog/echelix-solution-catalog.pdf"),
  cosell: publicAsset("catalog/echelix-cosell-catalog.pdf"),
} as const;

/** Pick the right catalog for the audience a visitor is browsing. */
export function catalogPdfFor(audience: "customer" | "microsoft"): string {
  return audience === "microsoft" ? CATALOG_PDF.cosell : CATALOG_PDF.customer;
}

// ---- Legal nav (used by footer + legal layout) --------------------------
export const LEGAL_LINKS: { href: string; label: string }[] = [
  { href: "/legal/privacy", label: "Privacy Policy" },
  { href: "/legal/terms", label: "Terms of Service" },
  { href: "/legal/accessibility", label: "Accessibility" },
  { href: "/legal/cookies", label: "Cookie Notice" },
];
