/**
 * Central site configuration — single source of truth for company/legal
 * identity, the conversion CTAs (book-a-call, pilot), and the generated
 * catalog-PDF download URLs.
 *
 * Imported by the footer, legal pages, the book-a-call modal, the pilot
 * form, and the catalog-PDF script. Keep values here, not inline.
 */

// ---- Company / legal identity -------------------------------------------
export const COMPANY = {
  legalName: "Echelix, LLC",
  shortName: "Echelix",
  // The demo hub is hosted at echelix.app; the corporate domain / contact
  // mailboxes are echelix.com (per the official Privacy Policy).
  domain: "echelix.app",
  siteUrl: "https://echelix.app",
  // Echelix, LLC operates a single U.S. office in Phoenix, Arizona.
  jurisdiction: "State of Arizona, United States",
  governingLaw: "State of Arizona, United States",
  location: "Phoenix, Arizona, United States",
  mailingAddress: "Echelix, LLC, 1141 E. Glendale Ave number 1004, Phoenix, AZ 85020, United States",
  tagline: "Modernize. Build Agentic Apps. Deliver Business Value.",
  // Contact addresses on the corporate domain (echelix.com).
  email: {
    general: "privacy@echelix.com",
    privacy: "privacy@echelix.com",
    legal: "privacy@echelix.com",
    accessibility: "privacy@echelix.com",
    security: "privacy@echelix.com",
    sales: process.env.SALES_NOTIFICATION_EMAIL || "sales@echelix.com",
  },
} as const;

// Effective/last-updated dates stamped on the legal pages.
// The Privacy Policy carries its own effective date from the official policy.
export const LEGAL_EFFECTIVE_DATE = "April 1, 2025";
export const PRIVACY_EFFECTIVE_DATE = "April 1, 2025";

// ---- Outlook Bookings (discovery / consultation call) -------------------
// Public Bookings page URL, e.g.
//   https://outlook.office365.com/owa/calendar/<your-booking>/bookings/
// Set NEXT_PUBLIC_BOOKINGS_URL in .env.local + Vercel. When unset, the
// book-a-call modal shows a graceful mailto fallback instead of an iframe.
export const BOOKINGS_URL = process.env.NEXT_PUBLIC_BOOKINGS_URL || "";

// ---- Catalog PDF (sales leave-behind) -----------------------------------
// The catalog PDFs are generated by scripts/gen-catalog-pdf.mjs and uploaded
// to Supabase Storage at deterministic (upserted) paths, so these public
// URLs are stable across regenerations.
function publicAsset(path: string): string {
  const base = (process.env.NEXT_PUBLIC_SUPABASE_URL || "").replace(/\/+$/, "");
  if (!base) return "";
  return `${base}/storage/v1/object/public/demo-assets/${path}`;
}

export const CATALOG_PDF = {
  customer: publicAsset("catalog/echelix-solution-catalog.pdf"),
  cosell: publicAsset("catalog/echelix-cosell-catalog.pdf"),
} as const;

/** Pick the right catalog for the audience a visitor is browsing. */
export function catalogPdfFor(audience: "customer" | "microsoft"): string {
  return audience === "microsoft" ? CATALOG_PDF.cosell : CATALOG_PDF.customer;
}

// ---- Legal nav (used by footer + legal layout) --------------------------
export const LEGAL_LINKS: { href: string; label: string }[] = [
  { href: "/legal/privacy", label: "Privacy Policy" },
  { href: "/legal/terms", label: "Terms of Use" },
  { href: "/legal/accessibility", label: "Accessibility" },
  { href: "/legal/cookies", label: "Cookie Policy" },
];
